## Setup

In [1]:
import sys 
import os
import IPython


# Env. vars to check if the notebook is running on colab, kaggle etc. 
IS_COLAB = "google.colab" in sys.modules 
IS_KAGGLE = "kaggle_secrets" in sys.modules 
IS_LOCAL = not (IS_COLAB or IS_KAGGLE)

if IS_COLAB:
    # Install the packages 
    %pip install -q -U tensorflow-addons
    %pip install -q -U transformers
    %pip install -q -U datasets
    print("You can safely ignore the package incompatibility errors.")
    # Mount the drive 
    from google.colab import drive 
    drive.mount("/drive")

# NOTE: This needs to be done for correct notebook behavior with the transformers 
# library 
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [2]:
import pandas as pd
import numpy as np
from tqdm import tqdm 

import random 
import shutil 
# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Pytorch imports 
import torch
import torch.nn as nn 
from torch.utils.data import Dataset, DataLoader

from typing import List, Tuple

# To plot pretty figures
import seaborn as sns
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

sns.set_theme()

In [3]:
# Project Paths
NOTEBOOK_NAME = "1.0-POC"
PROJECT_ROOT_DIR = "."

# --- Result dirs. 
OUTPUT_DIR = os.path.join(PROJECT_ROOT_DIR,"outputs",NOTEBOOK_NAME)
os.makedirs(OUTPUT_DIR,exist_ok=True)


LOGGING_DIR = os.path.join(OUTPUT_DIR,"logs")
os.makedirs(LOGGING_DIR,exist_ok=True)

In [4]:
# Setup logging for this notebook 
from LLMDialogue.utils.logging import configure_logger, create_file_handler, create_stream_handler
from LLMDialogue.utils.general import get_system_device
import logging

configure_logger(
    handlers=[
        create_stream_handler(logging_level=logging.WARNING), 
        create_file_handler(
            outdir=LOGGING_DIR, 
            logging_level=logging.DEBUG, 
            reset_outdir=False # Keep logs across runs. 
        )
    ]
)

In [5]:

GLOBAL_DEVICE = get_system_device()
# Shared env. vars. 
GLOBAL_SEED = 42 
RESET_OUTDIR = True
# Configuring env.
if  GLOBAL_SEED is not None:
    # to make this notebook's output stable across runs
    np.random.seed(GLOBAL_SEED) 
    torch.manual_seed(GLOBAL_SEED)
# NOTE: Should be mps for mac. 
GLOBAL_DEVICE

device(type='mps')

In [6]:
#Reset all but the logs dir in the output folder
from LLMDialogue.utils.general import remove_dir, get_subdirs_in_dir
if RESET_OUTDIR:
    subdirs = get_subdirs_in_dir(OUTPUT_DIR)
    for subdir in subdirs:
        if not subdir in ['logs']:
            remove_dir(subdir)

## Datasets

### In Conversation Corpus (ICC)

#### Variant - No Labels

This variant of the ICC does not include any conversation start or end or 
speaker labels.

In [7]:
from LLMDialogue.datasets import load
from LLMDialogue.datasets.ICC import objectify as ICCObjectify, ICCDatasetSplits

In [8]:
dset = load(
    dset_name="ICC", 
    config_name="no_labels"
)
print(dset)

{
    "date_created": "23_05_2024__13_16_57",
    "dset_name": "ICC",
    "variant_name": "no_labels",
    "version": "0.0.1",
    "data_dir": null,
    "data_files": {
        "train": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/data/raw/ICC/28_train_14_test_set/train",
        "test": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/data/raw/ICC/28_train_14_test_set/test"
    },
    "force_regenerate": false,
    "config_id": "6177b8867f970aef5e648c412b2434014347ee7638037e970b581a5c4942b019",
    "cache_dir": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/cache/datasets/6177b8867f970aef5e648c412b2434014347ee7638037e970b581a5c4942b019",
    "archive_dir": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/cache/datasets/6177b8867f970aef5e648c412b2434014347ee7638037e970b581a5c4942b019/archive",
    "compress_archive": true,
    "seed": 42,
    "verbose": false,
    "additional_special_tokens": {
        "eos_token": "<ts>"
    }
}

In [9]:
dset_splits = ICCObjectify(dset)
dset_splits.split_names

['train', 'test']

In [10]:
dset_splits.data_df_map['train']

,conversationName,conversationID,turnNumber,utterance
0,2018-02-04-session-1_nogaps_step1_GPT,0,0,all right
1,2018-02-04-session-1_nogaps_step1_GPT,0,1,hel
2,2018-02-04-session-1_nogaps_step1_GPT,0,2,hela hela this is go so weird to get used to
3,2018-02-04-session-1_nogaps_step1_GPT,0,3,i know i feel kinda
4,2018-02-04-session-1_nogaps_step1_GPT,0,4,all right um when's your first softball game
...,...,...,...,...
16825,2018-10-20-session-3_nogaps_step1_GPT,27,453,i'm like no high school junior or senior looke...
16826,2018-10-20-session-3_nogaps_step1_GPT,27,454,you<ts> i know exactly
16827,2018-10-20-session-3_nogaps_step1_GPT,27,455,not at my school
16828,2018-10-20-session-3_nogaps_step1_GPT,27,456,like it the the freshmen look like literal chi...
16829,2018-10-20-session-3_nogaps_step1_GPT,27,457,yeah the freshmen look like children and the s...

In [11]:
# Save the data dfs 
dset_name = dset.info().to_dict()['configs']['dset_name']
variant_name = dset.info().to_dict()['configs']['variant_name']
dset_splits.to_csv(
    outdir=f"{OUTPUT_DIR}/{dset_name}/{variant_name}"
)

{'train': './outputs/1.0-POC/ICC/no_labels/train.csv',
 'test': './outputs/1.0-POC/ICC/no_labels/test.csv'}

#### Variant - Special Labels

In [12]:
dset = load(
    dset_name="ICC", 
    config_name="labels"
)
print(dset)

{
    "date_created": "23_05_2024__13_16_58",
    "dset_name": "ICC",
    "variant_name": "labels",
    "version": "0.0.1",
    "data_dir": null,
    "data_files": {
        "train": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/data/raw/ICC/28_train_14_test_set/train",
        "test": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/data/raw/ICC/28_train_14_test_set/test"
    },
    "force_regenerate": false,
    "config_id": "16ca6817ab14e9b07e5907a0cf4231185131ca618d61c75a1d47fe4cd7759a2c",
    "cache_dir": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/cache/datasets/16ca6817ab14e9b07e5907a0cf4231185131ca618d61c75a1d47fe4cd7759a2c",
    "archive_dir": "/Users/muhammadumair/Documents/Repositories/mumair01-repos/GPT-Monologue-to-Dialogue/cache/datasets/16ca6817ab14e9b07e5907a0cf4231185131ca618d61c75a1d47fe4cd7759a2c/archive",
    "compress_archive": true,
    "seed": 42,
    "verbose": false,
    "additional_special_tokens": {
        "sp_start_token": "<START>",
        "sp_end_token": "<END>"
    }
}

In [13]:
dset_splits = ICCObjectify(dset)
dset_splits.split_names

['train', 'test']

In [14]:
dset_splits.data_df_map['train']

,conversationName,conversationID,turnNumber,utterance
0,2018-02-04-session-1_nogaps_step1_GPT,0,0,<START>
1,2018-02-04-session-1_nogaps_step1_GPT,0,1,<SP1> all right <SP1>
2,2018-02-04-session-1_nogaps_step1_GPT,0,2,<SP2> hel <SP2>
3,2018-02-04-session-1_nogaps_step1_GPT,0,3,<SP1> hela hela this is go so weird to get use...
4,2018-02-04-session-1_nogaps_step1_GPT,0,4,<SP2> i know i feel kinda <SP2>
...,...,...,...,...
21154,2018-10-20-session-3_nogaps_step1_GPT,27,567,<SP1> not at my school <SP1>
21155,2018-10-20-session-3_nogaps_step1_GPT,27,568,<SP2> like it the the freshmen look like liter...
21156,2018-10-20-session-3_nogaps_step1_GPT,27,569,<SP1> yeah the freshmen look like children and...
21157,2018-10-20-session-3_nogaps_step1_GPT,27,570,<SP1> like men <SP1>
21158,2018-10-20-session-3_nogaps_step1_GPT,27,571,<END>

In [15]:
# Save the data dfs 
dset_name = dset.info().to_dict()['configs']['dset_name']
variant_name = dset.info().to_dict()['configs']['variant_name']
dset_splits.to_csv(
    outdir=f"{OUTPUT_DIR}/{dset_name}/{variant_name}"
)

{'train': './outputs/1.0-POC/ICC/labels/train.csv',
 'test': './outputs/1.0-POC/ICC/labels/test.csv'}

### Speaker Identity

#### Variant - No Labels

In [16]:
from LLMDialogue.datasets.speakerIdentity import SpeakerIdentityDataSplits, objectify as SIObjectify

In [17]:
dset = load(
    dset_name="speakerIdentity",
    config_name="labels"
)

In [18]:
dset_splits = SIObjectify(dset)
dset_splits.split_names

['test']

In [19]:
dset_splits.data_df_map['test']

,conversationName,conversationID,turnNumber,utterance
0,30b,0,0,<START>
1,30b,0,1,<SP1> i haven't seen the keys anywhere <SP1>
2,30b,0,2,<SP2> have you <SP2>
3,30b,0,3,<END>
4,101bf,1,0,<START>
...,...,...,...,...
2995,18bd,748,3,<END>
2996,4bf,749,0,<START>
2997,4bf,749,1,<SP1> it's great that you could cover this shi...
2998,4bf,749,2,<SP1> for real <SP1>
2999,4bf,749,3,<END>

In [20]:
# Save the data dfs 
dset_name = dset.info().to_dict()['configs']['dset_name']
variant_name = dset.info().to_dict()['configs']['variant_name']
dset_splits.to_csv(
    outdir=f"{OUTPUT_DIR}/{dset_name}/{variant_name}"
)

{'test': './outputs/1.0-POC/speakerIdentity/labels/test.csv'}

#### Labels

In [21]:
dset = load(
    dset_name="speakerIdentity",
    config_name="labels"
)

In [22]:
dset_splits = SIObjectify(dset)
dset_splits.split_names

['test']

In [23]:
dset_splits.data_df_map['test']

,conversationName,conversationID,turnNumber,utterance
0,30b,0,0,<START>
1,30b,0,1,<SP1> i haven't seen the keys anywhere <SP1>
2,30b,0,2,<SP2> have you <SP2>
3,30b,0,3,<END>
4,101bf,1,0,<START>
...,...,...,...,...
2995,18bd,748,3,<END>
2996,4bf,749,0,<START>
2997,4bf,749,1,<SP1> it's great that you could cover this shi...
2998,4bf,749,2,<SP1> for real <SP1>
2999,4bf,749,3,<END>

In [24]:
# Save the data dfs 
dset_name = dset.info().to_dict()['configs']['dset_name']
variant_name = dset.info().to_dict()['configs']['variant_name']
dset_splits.to_csv(
    outdir=f"{OUTPUT_DIR}/{dset_name}/{variant_name}"
)

{'test': './outputs/1.0-POC/speakerIdentity/labels/test.csv'}

### Data Modules

These are required to be able to train the model

In [25]:
from LLMDialogue.dm.ICCdm import ICCHFLMDM
from LLMDialogue.dm.HFdm import HFLanguageModelingDM
from transformers import AutoTokenizer
from LLMDialogue.dm.ICCdm import ICCSpokenLanguageModelingDM
from LLMDialogue.tokenizers import SpokenDialogueTokenizer

#### ICC Language Modeling Data Module (Compatible with HuggingFace)

In [26]:
# Load the tokenizer here
tokenizer = AutoTokenizer.from_pretrained("gpt2")

In [27]:
# Load the dm and prepare it.
dm = ICCHFLMDM(
    dset_variant="labels", 
    tokenizer=tokenizer, 
    save_dir=OUTPUT_DIR
)
dm.prepare_data()
dm.setup('fit')

Map:   0%|          | 0/21159 [00:00<?, ? examples/s]

Map:   0%|          | 0/10559 [00:00<?, ? examples/s]

Map:   0%|          | 0/21159 [00:00<?, ? examples/s]

Map:   0%|          | 0/10559 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/2675 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1298 [00:00<?, ? examples/s]

#### ICC Spoken Language Modeling Data Module (Compatible with PL)

In [28]:
tokenizer = SpokenDialogueTokenizer()

Additional special tokens map:
	bos_token: <|endoftext|>
	eos_token: <ts>
	unk_token: <|endoftext|>
	pad_token: <|endoftext|>
	additional_special_tokens: ['<SP1>', '<SP2>']

NOTE: This tokenizer assumes that there are 2 speakers

In [29]:
dm = ICCSpokenLanguageModelingDM(
    dset_variant="labels", 
    tokenizer=tokenizer,
    save_dir=OUTPUT_DIR
)
dm.prepare_data()
dm.setup('fit')

Map:   0%|          | 0/21159 [00:00<?, ? examples/s]

Map:   0%|          | 0/743 [00:00<?, ? examples/s]

Map:   0%|          | 0/782 [00:00<?, ? examples/s]

Map:   0%|          | 0/802 [00:00<?, ? examples/s]

Map:   0%|          | 0/995 [00:00<?, ? examples/s]

Map:   0%|          | 0/1203 [00:00<?, ? examples/s]

Map:   0%|          | 0/674 [00:00<?, ? examples/s]

Map:   0%|          | 0/884 [00:00<?, ? examples/s]

Map:   0%|          | 0/1074 [00:00<?, ? examples/s]

Map:   0%|          | 0/821 [00:00<?, ? examples/s]

Map:   0%|          | 0/551 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/755 [00:00<?, ? examples/s]

Map:   0%|          | 0/758 [00:00<?, ? examples/s]

Map:   0%|          | 0/837 [00:00<?, ? examples/s]

Map:   0%|          | 0/727 [00:00<?, ? examples/s]

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Map:   0%|          | 0/903 [00:00<?, ? examples/s]

Map:   0%|          | 0/514 [00:00<?, ? examples/s]

Map:   0%|          | 0/773 [00:00<?, ? examples/s]

Map:   0%|          | 0/617 [00:00<?, ? examples/s]

Map:   0%|          | 0/1093 [00:00<?, ? examples/s]

Map:   0%|          | 0/693 [00:00<?, ? examples/s]

Map:   0%|          | 0/441 [00:00<?, ? examples/s]

Map:   0%|          | 0/698 [00:00<?, ? examples/s]

Map:   0%|          | 0/709 [00:00<?, ? examples/s]

Map:   0%|          | 0/485 [00:00<?, ? examples/s]

Map:   0%|          | 0/744 [00:00<?, ? examples/s]

Map:   0%|          | 0/572 [00:00<?, ? examples/s]

Map:   0%|          | 0/10559 [00:00<?, ? examples/s]

Map:   0%|          | 0/861 [00:00<?, ? examples/s]

Map:   0%|          | 0/1177 [00:00<?, ? examples/s]

Map:   0%|          | 0/385 [00:00<?, ? examples/s]

Map:   0%|          | 0/871 [00:00<?, ? examples/s]

Map:   0%|          | 0/772 [00:00<?, ? examples/s]

Map:   0%|          | 0/641 [00:00<?, ? examples/s]

Map:   0%|          | 0/859 [00:00<?, ? examples/s]

Map:   0%|          | 0/311 [00:00<?, ? examples/s]

Map:   0%|          | 0/751 [00:00<?, ? examples/s]

Map:   0%|          | 0/591 [00:00<?, ? examples/s]

Map:   0%|          | 0/1066 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/859 [00:00<?, ? examples/s]

Map:   0%|          | 0/715 [00:00<?, ? examples/s]

Map:   0%|          | 0/28 [00:00<?, ? examples/s]

You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Map:   0%|          | 0/28 [00:00<?, ? examples/s]

Map:   0%|          | 0/14 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/4163 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1917 [00:00<?, ? examples/s]

### Fine-tuning

#### GPT-2

The first model we want to funetune is GPT2, which is an instance of a 
language model from hugging face.

In [30]:
from LLMDialogue.models import GPT2

In [31]:
# Instantiate and load the model 
gpt2 = GPT2(seed=GLOBAL_SEED)
gpt2.load()
gpt2.to(GLOBAL_DEVICE)
print(gpt2)

Base model: GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50258, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D()
          (c_proj): Conv1D()
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D()
          (c_proj): Conv1D()
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50258, bias=False)
)
Base tokenizer: GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<|endoftext|>', 'unk_token': '<|endoftext|>', 'pad_token': '<PAD>'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	50257: AddedToken("<PAD>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
device: mps

In [32]:
# Now, finetune the model using the appropriate data module 
# Load the dm and prepare it.
dm = ICCHFLMDM(
    dset_variant="labels", 
    tokenizer=gpt2.tokenizer, 
    save_dir=OUTPUT_DIR
)

In [33]:
# Now, finetune the model. 
# gpt2.finetune(
#     dm=dm, 
#     save_dir=f"{OUTPUT_DIR}/models/gpt2",
#     num_train_epochs=1
# )

### TurnGPT

In [34]:
from LLMDialogue.models import TurnGPT

In [35]:
turngpt = TurnGPT(seed=GLOBAL_SEED)
turngpt.load(model_head="LMHead")
turngpt.to(device=GLOBAL_DEVICE)
print(turngpt)

/opt/miniconda3/envs/gpt/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Additional special tokens map:
	bos_token: <|endoftext|>
	eos_token: <ts>
	unk_token: <|endoftext|>
	pad_token: <|endoftext|>
	additional_special_tokens: ['<SP1>', '<SP2>']

NOTE: This tokenizer assumes that there are 2 speakers
Initialized special wte for <ts> to average of ['!', '?', '.']
This will make the <ts> semantically closer to ['!', '?', '.']
Base model: TurnGPTLMHeadModel(
  (_transformer): GPT2LMHeadModel(
    (transformer): GPT2Model(
      (wte): Embedding(50260, 768)
      (wpe): Embedding(1024, 768)
      (drop): Dropout(p=0.1, inplace=False)
      (h): ModuleList(
        (0-11): 12 x GPT2Block(
          (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (attn): GPT2Attention(
            (c_attn): Conv1D()
            (c_proj): Conv1D()
            (attn_dropout): Dropout(p=0.1, inplace=False)
            (resid_dropout): Dropout(p=0.1, inplace=False)
          )
          (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
          (mlp): GPT2MLP(
            (c_fc): Conv1D()
            (c_proj): Conv1D()
            (act): NewGELUActivation()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    )
    (lm_head): Linear(in_features=768, out_features=50260, bias=False)
  )
)
Base tokenizer: GPT2TokenizerFast(name_or_path='gpt2', vocab_size=50257, model_max_length=1e+30, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<|endoftext|>', 'eos_token': '<ts>', 'unk_token': '<|endoftext|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<SP1>', '<SP2>']}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	50256: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50257: AddedToken("<ts>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50258: AddedToken("<SP1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50259: AddedToken("<SP2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
device: mps

In [36]:
# Load the appropriate dm and finetune
dm = ICCSpokenLanguageModelingDM(
    dset_variant="labels", 
    tokenizer=tokenizer,
    save_dir=OUTPUT_DIR
)

Map:   0%|          | 0/21159 [00:00<?, ? examples/s]

Map:   0%|          | 0/743 [00:00<?, ? examples/s]

Map:   0%|          | 0/782 [00:00<?, ? examples/s]

Map:   0%|          | 0/802 [00:00<?, ? examples/s]

Map:   0%|          | 0/995 [00:00<?, ? examples/s]

Map:   0%|          | 0/1203 [00:00<?, ? examples/s]

Map:   0%|          | 0/674 [00:00<?, ? examples/s]

Map:   0%|          | 0/884 [00:00<?, ? examples/s]

Map:   0%|          | 0/1074 [00:00<?, ? examples/s]

Map:   0%|          | 0/821 [00:00<?, ? examples/s]

Map:   0%|          | 0/551 [00:00<?, ? examples/s]

Map:   0%|          | 0/844 [00:00<?, ? examples/s]

Map:   0%|          | 0/755 [00:00<?, ? examples/s]

Map:   0%|          | 0/758 [00:00<?, ? examples/s]

Map:   0%|          | 0/837 [00:00<?, ? examples/s]

Map:   0%|          | 0/727 [00:00<?, ? examples/s]

Map:   0%|          | 0/467 [00:00<?, ? examples/s]

Map:   0%|          | 0/903 [00:00<?, ? examples/s]

Map:   0%|          | 0/514 [00:00<?, ? examples/s]

Map:   0%|          | 0/773 [00:00<?, ? examples/s]

Map:   0%|          | 0/617 [00:00<?, ? examples/s]

Map:   0%|          | 0/1093 [00:00<?, ? examples/s]

Map:   0%|          | 0/693 [00:00<?, ? examples/s]

Map:   0%|          | 0/441 [00:00<?, ? examples/s]

Map:   0%|          | 0/698 [00:00<?, ? examples/s]

Map:   0%|          | 0/709 [00:00<?, ? examples/s]

Map:   0%|          | 0/485 [00:00<?, ? examples/s]

Map:   0%|          | 0/744 [00:00<?, ? examples/s]

Map:   0%|          | 0/572 [00:00<?, ? examples/s]

Map:   0%|          | 0/10559 [00:00<?, ? examples/s]

Map:   0%|          | 0/861 [00:00<?, ? examples/s]

Map:   0%|          | 0/1177 [00:00<?, ? examples/s]

Map:   0%|          | 0/385 [00:00<?, ? examples/s]

Map:   0%|          | 0/871 [00:00<?, ? examples/s]

Map:   0%|          | 0/772 [00:00<?, ? examples/s]

Map:   0%|          | 0/641 [00:00<?, ? examples/s]

Map:   0%|          | 0/859 [00:00<?, ? examples/s]

Map:   0%|          | 0/311 [00:00<?, ? examples/s]

Map:   0%|          | 0/751 [00:00<?, ? examples/s]

Map:   0%|          | 0/591 [00:00<?, ? examples/s]

Map:   0%|          | 0/1066 [00:00<?, ? examples/s]

Map:   0%|          | 0/700 [00:00<?, ? examples/s]

Map:   0%|          | 0/859 [00:00<?, ? examples/s]

Map:   0%|          | 0/715 [00:00<?, ? examples/s]

In [37]:
# turngpt.finetune(
#     dm=dm,
#     save_dir=f"{OUTPUT_DIR}/models/turngpt",
#     max_epochs=1
# )

### Pipelines

In [38]:
from LLMDialogue.pipelines import CPPipelineConfig, CPPipeline

In [39]:
gpt2 = GPT2(seed=GLOBAL_SEED)
gpt2.load()

In [40]:
# Create the pipeline config 
config = CPPipelineConfig(
    model = gpt2, 
    utterances=['this is is a text'],
    N = -1,
    context_buffer_size=512,   
)

In [42]:
# Now, init the pipeline 
pipe = CPPipeline(config)
pipe.run()

Processing turns: 100%|██████████| 1/1 [00:07<00:00,  7.87s/it]

In [45]:
df = pd.DataFrame(pipe.info().data)
df

   turn_no  word_no       context  word  last_word_prob
0        0        1          this    is    7.019224e-14
1        0        2       this is    is    0.000000e+00
2        0        3    this is is     a    8.809402e-37
3        0        4  this is is a  text    0.000000e+00

In [46]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [52]:
model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")
word = "this"

In [55]:
toks = tokenizer.encode(word,return_tensors="pt")
model(toks)

CausalLMOutputWithCrossAttentions(loss=None, logits=tensor([[[-31.8387, -30.9853, -34.4230,  ..., -39.7514, -38.6847, -32.3073]]],
       grad_fn=<UnsafeViewBackward0>), past_key_values=((tensor([[[[-1.1436e+00,  2.0865e+00,  1.0915e+00,  5.2886e-01,  6.7749e-01,
            2.1998e-01,  3.3289e-01,  5.0914e-01, -1.5674e+00,  7.3908e-01,
           -5.5447e-01, -4.3670e-01,  6.7484e-01,  7.6756e-02, -3.3582e-01,
           -1.0729e-01,  5.1017e-01, -8.2771e-02,  2.6644e+00, -8.4814e-03,
           -2.0417e+00,  9.1725e-02, -6.9554e-01, -1.3793e+00, -2.0295e-01,
           -8.7571e-01, -4.5975e-01, -2.4336e-01, -3.8781e-01, -7.2261e-01,
            1.1481e+00, -1.0246e+00, -1.0068e+00,  3.3189e-01, -2.0250e-01,
            2.5039e-01,  1.0650e+00,  8.2601e-01,  1.6686e-01,  4.5301e-01,
           -2.1656e-01,  3.3721e-04, -8.5817e-01,  2.5071e-02, -3.5411e-01,
           -2.8066e-01,  7.6596e-01,  2.4335e-01, -6.4883e-01,  2.7056e-01,
            7.4140e-01, -4.9807e-01,  9.9808e-01,  3.7535e-02,  2.9059e-01,
            1.3077e+00, -3.7493e-01, -7.0622e-01,  2.1920e-01,  4.5837e-01,
           -1.1001e+00, -1.2483e+00, -6.9566e-01,  1.6006e+00]],

         [[ 3.6071e-01,  2.0304e-01, -8.6156e-01,  8.0084e-01, -3.1401e-01,
           -2.1079e-01,  2.2239e-01,  8.3510e-01, -5.2787e-01,  1.9057e-01,
            1.3930e-01,  8.1503e-01, -4.3785e-01, -5.1812e-01, -1.7435e+00,
            1.3206e-01, -6.2813e-01,  6.3125e-01,  1.5060e-01,  7.5028e-01,
            3.4183e-01,  4.8227e-01,  7.1076e-01,  3.3122e-01,  9.1513e-01,
            8.9361e-02,  3.9541e-02, -4.0122e-01, -5.1179e-01, -5.6410e-01,
           -4.5489e-01, -1.4556e+00,  1.4431e-02,  1.2215e-01,  9.1238e-01,
           -1.0452e-01, -8.6611e-01, -1.3362e+00,  1.2046e+00,  2.3779e-01,
           -2.4584e-01, -1.2134e+00,  3.1263e-02, -3.4511e-01,  7.5022e-02,
           -8.4621e-01,  2.0497e-02,  1.5675e-01, -3.9141e-01, -1.3898e+00,
            3.5232e-01,  4.0142e-02, -1.8312e+00,  4.4041e-01, -6.1559e-01,
            8.1177e-01,  7.7128e-01,  1.4548e+00, -1.0785e-01,  7.5886e-02,
           -1.3407e+00,  6.4923e-01,  2.1252e+00, -1.5015e-01]],

         [[-1.9523e-01, -1.1913e-01,  1.0264e+00,  1.2748e+00,  2.3908e-01,
           -6.4838e-01, -1.2855e+00,  4.7313e-01,  6.6542e-01,  7.8856e-01,
            4.0431e-01, -6.0882e-01, -3.1930e-01,  5.4151e-01,  7.8737e-01,
            3.1336e-01,  9.6328e-01,  4.3954e-01, -1.0206e+00, -1.1974e+00,
            6.5773e-01,  1.5743e-01, -1.1877e+00,  1.4588e-01, -1.3164e+00,
           -5.9114e-01, -6.5735e-01,  1.0635e+00,  6.4039e-01, -1.2007e+00,
            3.6165e-01, -7.0452e-01,  1.5229e-02, -1.1346e+00,  4.0248e-01,
           -8.2224e-01,  1.9328e-01, -1.4860e+00,  1.9077e+00,  5.6245e-01,
           -5.7206e-01, -5.1842e-01, -1.0170e+00,  7.1178e-01, -9.5204e-02,
            1.2012e+00, -2.2322e-01, -1.0472e+00, -4.5370e-01,  8.7982e-01,
            3.7871e-01,  1.0434e+00, -1.0145e+00, -9.6769e-02, -7.4726e-01,
            3.8676e-01, -4.2638e-01, -1.7794e-01,  1.1476e+00,  4.7239e-01,
            8.2669e-01, -1.4734e+00, -1.9029e+00,  9.1331e-01]],

         [[-1.5769e+00, -7.2402e-02, -8.7215e-01,  2.6282e+00, -2.3906e+00,
           -2.2439e+00, -4.0346e-01, -1.2761e+00, -1.0261e+00,  2.3436e-01,
           -4.0313e-01, -2.7365e-01,  1.4874e+00, -1.8966e+00,  7.9976e-01,
            1.0325e+00,  3.0090e-02, -7.7687e-01, -6.6529e-01,  2.0149e-01,
           -1.3198e+00, -5.6991e-01, -1.0611e+00, -6.3618e-01,  6.9148e-02,
            1.1921e+00, -1.2195e-01,  1.4922e-01,  3.4391e-01, -2.2513e+00,
            2.5204e-01,  7.0391e-01,  1.1965e+00, -2.3850e+00, -1.5475e+00,
           -1.2010e+00,  4.6536e-01,  1.0346e+00, -1.2815e+00,  1.7696e-01,
           -1.7188e-01, -6.5022e-01, -8.2907e-01,  5.8359e-01, -1.7627e-01,
           -6.5248e-01, -5.6057e-01,  3.2114e-01,  7.4314e-01,  3.0420e+00,
            3.3633e-01,  1.0201e+00, -1.3454e+00, -2.6012e+00, -4.2724e-01,
            2.8176e+00,  2.3062e+00, -1.6836e+00,  3.5752e-01, -3.0628e-01,
           -1.0042e+00,  1.4232e+00,  1.5120e+00,  1.0209e+00]],

         [[ 1.0363e+00,  6.2437e-01,  4.8297e-01,  5.3240e-01, -3.5378e-01,
           -8.1594e-01, -6.5035e-01,  1.4259e-01,  3.5647e-01, -3.4114e-01,
            4.1990e-01,  7.7847e-01,  1.8264e+00, -9.2526e-01, -1.2853e-01,
           -5.7889e-01,  7.4260e-02, -5.1244e-01, -1.0637e+00,  1.0899e+00,
           -1.1491e+00, -1.5148e+00, -6.9421e-01, -7.9849e-01,  1.7637e+00,
            6.0895e-01,  5.6719e-01,  8.5875e-01, -1.3529e+00,  4.6416e-02,
            4.7008e-01,  1.2103e+00,  2.6775e-01, -6.7416e-01, -1.2863e+00,
            1.3305e+00, -2.2291e-01,  1.7044e-01,  5.4990e-01,  1.7223e+00,
            9.4756e-01, -6.8073e-01,  3.3169e+00, -1.9877e+00, -1.7652e+00,
            1.9924e+00, -3.5144e-01,  5.3654e-01, -6.4471e-01,  3.9745e-01,
           -2.7706e-01, -3.8071e-01, -8.0589e-01, -1.3238e+00,  8.5577e-01,
           -1.2053e-01, -3.9398e-01, -3.0128e-01,  1.9585e+00, -8.1667e-01,
           -7.6025e-01,  5.3255e-02,  1.9567e+00, -9.4860e-01]],

         [[-7.9120e-01, -1.9651e+00,  1.2175e+00, -7.3506e-01,  1.8801e+00,
            8.1074e-01,  1.3804e-01,  3.6904e-02,  8.1380e-01,  8.0460e-01,
            1.9308e+00, -1.1341e+00, -2.6222e+00,  1.9200e+00,  7.7027e-01,
           -2.1402e+00,  1.5625e-01, -1.0429e+00,  8.0968e-01, -1.9524e+00,
           -1.7059e+00,  1.6643e+00, -1.8319e+00, -6.4676e-03,  2.8395e+00,
           -9.5954e-01, -2.1309e+00,  2.3698e-01,  1.6200e+00, -1.2863e+00,
            1.0707e+00, -6.6910e-01, -2.4648e+00,  2.5228e-01,  1.9497e+00,
            3.3117e+00, -1.8473e+00, -2.6594e+00, -1.7660e-01,  1.1527e+00,
           -2.9135e+00,  6.3452e-01,  4.7240e-01,  3.3920e+00,  9.6173e-02,
            8.8839e-01, -1.9246e+00,  1.1179e-01,  5.0642e-01,  8.7575e-01,
           -1.8238e+00,  1.1486e-01,  2.6223e-01, -3.5910e+00,  2.3568e+00,
            3.7409e-01, -2.3488e+00, -1.9298e-01, -1.5766e-01, -2.5822e-01,
           -4.6888e+00, -1.7110e+00,  3.5416e+00, -1.2651e+00]],

         [[ 4.2651e-01, -1.8670e+00, -5.5520e-01,  1.4623e+00, -8.8961e-02,
            1.2023e+00,  1.2953e+00, -3.8822e-01,  8.2905e-02,  2.1673e+00,
            1.8020e+00, -5.5285e-01,  4.5269e-01,  6.0044e-01,  1.0541e+00,
            4.0546e-01,  1.3520e+00, -2.9247e-01, -6.4500e-02,  1.4615e+00,
            6.8452e-01, -3.3336e-01,  9.1605e-01, -1.2363e+00, -3.3841e-01,
            1.8782e+00, -2.4173e-01,  3.2224e-01, -9.0098e-01, -9.9409e-01,
            7.7495e-01, -1.3283e-01,  5.3568e-01, -3.8337e-01,  4.5981e-01,
            1.3322e+00, -5.7691e-01,  1.7018e+00, -1.1089e+00, -5.9082e-01,
            1.3045e+00,  1.1576e+00,  1.3931e+00,  1.8653e+00, -3.7776e-01,
           -1.5925e+00,  6.4845e-01,  3.7671e-01, -1.0450e+00, -6.5003e-01,
            5.0973e-02,  4.1136e-01,  7.1524e-01, -1.2569e+00,  8.4944e-01,
            3.9236e-01,  7.8646e-01,  1.3471e+00,  1.3825e+00,  1.0712e-01,
           -7.3978e-01, -8.6671e-01,  1.2425e+00, -9.6367e-01]],

         [[-4.3888e-01,  1.7335e+00, -3.6819e-01,  3.5817e-01,  1.8220e-02,
            8.8113e-01,  1.3716e+00,  1.4532e+00, -2.9520e-01,  6.7899e-01,
           -7.5829e-01, -8.2005e-01, -9.4016e-01, -8.7444e-01, -8.8683e-01,
           -4.1155e-01,  1.6429e-01, -2.2417e-01,  1.7531e+00, -2.4170e+00,
            9.9008e-02,  2.0121e-01,  2.9074e-01,  3.2057e+00,  6.6877e-01,
            1.9941e+00,  1.1890e+00,  1.1529e+00, -3.0128e-01,  9.3452e-01,
            9.0950e-01, -1.5122e+00,  1.4481e+00,  5.7421e-01,  5.3623e-01,
            8.8946e-01, -1.1400e+00,  4.8773e-01, -7.3298e-01,  1.0157e+00,
            4.2087e-01,  1.6383e+00,  6.9884e-01,  1.7508e-01, -5.6064e-01,
            8.5216e-01, -4.3295e-01, -1.2190e+00, -3.6738e-01, -1.9107e+00,
            1.2258e-02,  7.2516e-01, -3.1651e-01,  4.2287e-01,  1.9240e+00,
           -1.6539e-01,  2.8662e-01, -2.4480e-01,  8.4428e-01, -4.0921e-01,
            8.8574e-02,  2.6149e+00, -4.0054e-02, -2.7829e-01]],

         [[-4.1544e-01, -1.5022e+00,  2.2724e+00, -5.3347e-02,  1.6493e+00,
           -4.1560e-01,  1.3267e+00,  5.6962e-01, -1.3545e+00,  2.2774e-01,
            7.4293e-01,  4.2556e-02, -1.0496e-01, -1.2028e+00,  6.1713e-01,
            5.7838e-02,  2.2927e-01, -6.6657e-01, -1.0530e-01, -9.0256e-01,
           -3.4018e-01, -1.3518e+00, -3.7989e-01, -4.3162e-01, -5.4245e-01,
           -1.1624e+00, -7.8476e-01,  1.4173e+00, -4.1919e-01, -6.9880e-02,
            1.1319e+00, -1.4257e+00, -1.9351e+00, -3.3720e-01, -6.2854e-01,
            1.9161e-02, -1.4802e+00,  2.5935e-01,  1.5782e-01,  2.2190e-02,
           -5.5911e-01, -4.5498e-01,  7.6373e-01,  5.4297e-01,  8.7254e-01,
            1.5168e+00,  7.8828e-01, -6.5082e-01, -3.2182e-02, -5.2210e-01,
            1.2320e+00,  3.2744e-03,  7.8649e-01,  1.5041e+00, -1.0487e-01,
            1.5871e+00,  5.5632e-01,  8.1424e-01, -6.4244e-01, -1.9576e+00,
            9.8458e-01,  1.9036e+00,  1.6234e+00,  3.8215e-01]],

         [[ 6.4446e-01, -1.7246e-01, -3.7272e-01,  8.0034e-02,  2.6815e-01,
           -1.2281e-01, -5.0349e-01,  2.1715e-01, -1.0678e+00,  7.1753e-01,
           -5.6283e-01, -1.4911e+00, -1.7213e-01, -1.2162e+00, -2.0147e+00,
            2.1910e+00, -1.7818e-01,  2.1338e-01,  4.4775e-01,  3.4772e-01,
            1.5786e+00, -6.4935e-02,  3.2226e-01, -2.9391e-01, -2.8682e-01,
           -1.4998e+00, -7.9396e-02,  2.2783e-01, -6.6426e-02, -2.1157e-01,
            8.4186e-01,  2.5301e-01,  2.1291e-01,  1.5054e-01,  7.3939e-01,
           -8.4137e-01,  2.6216e-02,  1.1020e-01,  4.4544e-01,  1.1688e+00,
            2.7959e-01,  1.3649e+00,  2.3788e-01, -4.7115e-02,  1.0792e+00,
           -3.2349e-01,  1.9059e+00, -4.0997e-01, -4.3724e-01, -5.1802e-01,
           -5.6793e-02,  4.4377e-01, -1.1559e+00, -4.7809e-01, -5.6133e-01,
            1.3757e-01, -7.2347e-02, -5.5839e-01,  5.4526e-01, -6.4222e-01,
            1.0827e-01,  3.5627e-01,  6.1325e-01,  4.2078e-01]],

         [[ 1.4932e+00,  1.1508e+00, -2.4704e-01, -9.6379e-01, -3.4326e-01,
            4.4852e-02, -9.6889e-01,  2.1749e+00,  6.5334e-01,  5.0251e-02,
            7.3446e-02, -8.5396e-01,  7.7669e-01,  2.0663e-01, -4.0134e-01,
           -4.8480e-02,  3.4308e-01, -4.1401e-01,  1.5318e+00, -3.2293e-01,
           -1.5626e+00,  3.2831e-01, -2.7597e-01,  1.7687e+00,  6.7370e-01,
            1.1380e-01,  8.0865e-01, -3.0664e-01, -3.5473e-01, -5.1603e-01,
            3.8281e-01,  1.5669e+00, -3.8434e-01, -6.7232e-01,  1.6649e-02,
            3.6231e-01, -4.5645e-01, -1.2225e+00,  5.4135e-01,  4.2136e-02,
            5.4153e-01, -5.5652e-01, -6.8441e-01, -1.4003e+00,  1.4145e-01,
            7.7094e-01, -8.4231e-01,  2.7931e+00, -4.9920e-01, -6.7782e-01,
           -2.7794e-01,  3.2931e-01,  8.4255e-02,  1.0743e+00, -7.8259e-01,
           -8.4414e-01, -6.5840e-01,  9.1570e-01, -5.2986e-01,  4.0508e-01,
            1.4795e+00, -7.6321e-02,  9.8715e-01, -1.3522e+00]],

         [[ 8.1262e-01,  4.0266e-02,  5.6926e-01, -8.0045e-01,  1.3236e+00,
           -9.2673e-01, -5.4083e-01, -1.3738e-01, -1.0446e+00, -5.1854e-01,
            1.8504e-01, -4.3110e-01, -3.4908e-01, -4.1289e-01, -4.4537e-01,
            1.4698e+00,  1.3539e-01,  3.0950e-01, -3.3115e-01,  1.9629e+00,
           -4.5955e-01, -1.0320e+00,  1.1663e-01, -7.4157e-01, -3.5051e-01,
            3.5258e-01, -3.4287e-01, -5.8713e-01, -8.3051e-02, -9.0954e-02,
            3.7818e-03,  9.2777e-02,  3.1026e-01, -7.1623e-01,  4.9266e-01,
           -1.0807e+00,  1.5994e+00,  6.1982e-02, -2.3923e-01,  1.5386e-02,
            8.1809e-02, -8.9981e-01, -1.0565e-01,  3.2945e-01, -5.3187e-02,
            1.6419e-01,  1.0834e-02,  3.5095e-01, -7.8842e-01, -3.6841e-01,
           -3.2714e-01, -9.4807e-01,  2.2417e-01, -4.5690e-01, -5.5608e-01,
            2.8390e-01,  2.1206e+00,  3.4075e-01,  1.0819e+00, -5.8217e-01,
            2.1533e-02, -6.9822e-01,  4.0799e-01,  1.7316e+00]]]],
       grad_fn=<PermuteBackward0>), tensor([[[[ 1.1442e-01,  8.9396e-02,  9.9032e-02,  3.1593e-02, -6.5517e-03,
           -3.7912e-01, -2.1166e-01, -1.1714e-01, -1.0606e-01, -1.8073e-01,
           -1.0420e-01,  6.0319e-02, -1.2481e-01, -2.5101e-01,  2.0690e-01,
           -7.7313e-02,  1.5710e-01,  7.8931e-02, -7.4856e-02, -9.8893e-02,
           -2.1232e-01,  4.1085e-03,  1.5723e-01,  5.2028e-03, -3.1169e-02,
           -3.7626e-02,  3.6876e-02, -1.4043e-01, -1.9600e-02, -1.2618e-01,
           -2.7398e-01, -6.0132e-02,  1.9863e-01,  1.3712e-01, -2.1763e-01,
           -4.5357e-02,  6.8372e-02,  3.6661e-02, -2.1722e-01, -1.0273e-02,
           -3.4776e-01, -1.0803e-01, -1.7008e-02,  5.7151e-03,  2.5314e-01,
            1.2218e-01,  1.3487e-01, -7.2773e-02,  2.0118e-02, -2.1119e-02,
            1.6236e-01, -4.0851e-02, -1.3580e-01, -1.2717e-01,  1.1784e-01,
            1.6906e-01,  3.9087e-02, -4.5503e-02,  7.4519e-02, -7.2785e-02,
            7.7473e-02,  4.8486e-02,  4.2911e-02, -5.0545e-02]],

         [[ 3.8719e-01,  1.8677e-01, -2.0963e-01,  3.0275e-01,  2.7348e-02,
            1.0430e-01, -2.2137e-01, -4.5898e-02, -7.1045e-02,  1.6200e-01,
           -2.8606e-02, -4.6112e-01, -1.5601e-01, -4.7375e-01,  1.0858e-01,
           -2.5406e-02, -4.2494e-02, -2.4878e-01, -2.1130e-01,  4.6482e-02,
           -2.3469e-03, -1.2906e-01, -2.2674e-01,  9.4429e-02, -1.1361e-01,
            2.6856e-02, -2.6276e-01, -2.7785e-01, -1.5555e-01, -2.2335e-01,
            2.9201e-01, -1.5427e-01, -4.9896e-01, -1.3107e-01, -3.5035e-01,
            1.8326e-01,  1.2521e-01, -2.2456e-01, -2.1860e-01, -1.7776e-01,
           -8.1987e-02, -2.2819e-01, -4.1516e-01,  2.9230e-01,  2.2977e-01,
            3.1354e-01,  7.0365e-02, -1.2759e-01,  4.0778e-02, -4.9221e-02,
            2.4636e-01, -1.2880e-01, -8.9054e-02,  1.7346e-01,  6.2120e-03,
            1.3312e-01,  8.0339e-02, -2.7732e-01, -1.0860e-01,  1.1926e-01,
           -2.0372e-01, -6.3338e-01, -2.9971e-01,  1.2311e-01]],

         [[-1.7204e-01, -2.4489e-02, -9.7592e-02,  4.8507e-02,  1.0012e-01,
           -1.0255e-01,  6.6974e-03,  1.3682e-01,  8.6965e-01, -1.0447e-03,
            3.7663e-02, -5.2822e-02,  3.6153e-02, -7.8479e-02, -6.8212e-02,
            4.7815e-02,  1.6128e-01,  1.0978e-01,  1.1696e-01,  6.2298e-02,
           -2.8779e-01,  4.1625e-01,  2.9551e-02,  6.1943e-02,  1.2287e-01,
           -2.8975e-02, -1.4154e-01,  1.5283e-01, -1.9735e-01,  6.5437e-02,
            2.6856e-02,  7.4355e-02, -5.9881e-02,  4.8283e-02,  5.5689e-02,
           -2.7734e-03,  6.5154e-02, -2.8124e-02, -6.9452e-02, -2.0751e-02,
            8.6273e-03, -3.8028e-02,  1.0966e-01, -1.7726e-01,  6.4400e-02,
           -1.7326e-02, -5.4610e-02,  1.0734e-01, -1.1070e-01, -4.2118e-02,
            9.6566e-02, -2.1716e-02,  2.4877e-02, -3.8660e-02, -5.6640e-02,
            9.5492e-02, -2.3029e-02, -3.6435e-03, -1.4319e-01,  1.0278e-01,
            1.7637e-02, -7.4125e-02,  9.2519e-02,  1.4184e-02]],

         [[-8.9132e-02, -4.5090e-02,  2.1319e-02, -2.5989e-01, -2.7445e-01,
           -1.1144e-01, -1.2418e-01,  6.0431e-02,  5.9135e-02, -1.2412e-01,
            9.3840e-02,  1.3891e-02,  1.4007e-01,  7.6053e-02, -1.8489e-01,
           -1.5452e-01,  1.5836e-01,  3.5737e-02, -8.2672e-03, -1.5419e-02,
           -2.7558e-02,  1.0244e-01, -7.0996e-02, -4.3789e-02,  2.3623e-01,
            8.2100e-02,  2.7711e-02, -3.5869e-01, -1.2679e-01, -4.4244e-02,
            1.6267e-01,  2.5919e-01, -8.4753e-03,  4.9095e-02, -2.1710e-01,
            1.7769e-02, -9.5443e-02,  2.1949e-03, -6.5326e-02,  3.9887e-01,
           -6.0915e-02,  2.9726e-01, -1.4496e-01, -7.8206e-02,  5.1924e-02,
           -1.3231e-01, -1.1225e-01,  9.3669e-02, -3.4359e-01,  6.8477e-02,
           -4.0413e-02,  2.0997e-02, -1.1437e-01,  3.0417e-02,  3.6033e-02,
            6.1437e-02, -2.3670e-02,  6.6225e-02, -5.9950e-02,  1.3008e-01,
            1.2597e-01,  1.6711e-01,  1.7827e-01,  1.2052e-01]],

         [[-1.4890e-01, -1.9047e-02,  8.7032e-04, -5.6714e-02,  6.2804e-02,
            5.1833e-02, -3.3875e-02, -7.8006e-02,  2.1385e-01, -3.6294e-02,
           -2.8756e-04, -5.5521e-02, -9.6785e-03,  2.2821e-02, -2.2705e-02,
           -4.4499e-01, -7.1758e-02, -1.8417e-01, -2.4733e-01, -6.2619e-02,
            1.5517e-01, -1.7745e-01,  1.0927e-01,  1.9926e-02,  2.0940e-01,
            5.6762e-02, -1.5029e-01, -1.4806e-03, -1.1731e-01,  1.9252e-01,
            3.0970e-01,  1.7741e-01,  6.2207e-03,  4.9596e-01, -1.3770e-01,
            3.8985e-01,  1.4080e-01,  4.6466e-02,  7.8106e-02, -3.8426e-02,
            5.2293e-02, -2.1677e-02, -1.7372e-02,  1.2870e-02,  1.9634e-02,
           -2.1695e-01, -1.1858e-01, -7.4245e-02, -1.6868e-01, -3.7806e-02,
           -1.7103e-01,  5.6078e-02, -8.3052e-02,  1.9846e-01,  2.1170e-02,
            7.3097e-02,  2.2459e-02, -5.2493e-02,  2.8130e-02, -8.4816e-02,
            6.8532e-02, -5.8660e-02, -1.2175e-01,  2.1135e-01]],

         [[-2.0231e-01, -1.0787e-01, -3.4918e-01,  3.1779e-01, -1.4938e-01,
            2.3119e-01, -2.7794e-01, -2.6127e-01,  1.3002e-01,  3.9408e-02,
           -2.3750e-01,  3.4438e-01,  4.2301e-02,  4.8640e-02,  1.4807e-01,
           -3.5734e-01, -2.3954e-01, -3.5962e-01, -2.3471e-02,  1.4980e-01,
            2.1976e-01, -2.2117e-01,  3.3923e-01, -2.6308e-01, -2.7883e-01,
           -2.2519e-01,  5.7161e-03, -6.7074e-02,  1.1848e-01, -7.3136e-02,
           -1.5610e-01, -1.2001e-01, -3.4272e-01,  1.2191e-01, -1.0814e-01,
            8.8820e-02,  2.1344e-01, -4.4484e-01, -4.7815e-02, -4.8294e-02,
           -3.7408e-02, -2.2533e-01,  2.2031e-01, -1.1995e-01,  5.0530e-02,
           -1.7143e-01, -3.3120e-01, -1.0241e-01, -7.5802e-02, -1.0182e-01,
           -1.3942e-01, -1.5182e-01,  4.6633e-02, -1.4866e-01, -3.7349e-01,
           -2.0041e-01,  1.7869e-01,  4.7993e-01, -1.9291e-02,  1.9433e-01,
           -4.0863e-01,  1.9470e-01, -6.5119e-02, -4.6829e-03]],

         [[ 5.2283e-03, -3.4552e-02,  3.7441e-02, -1.1111e-02,  7.4487e-03,
           -4.0702e-02,  8.1813e-02,  8.5878e-02, -5.6972e-02,  5.5195e-04,
           -1.2510e-01, -1.3551e-01,  7.2712e-02, -9.8222e-03,  1.3582e-01,
            5.2684e-02, -8.3669e-02, -1.2468e-01, -1.6422e-01,  7.4909e-03,
           -8.1995e-02,  1.1205e-01, -1.5852e-01,  4.8157e-02, -6.3478e-02,
           -6.8465e-02, -9.9542e-02, -8.2605e-02, -5.7119e-02, -2.4784e-01,
            3.2126e-02,  1.5270e-01, -3.4437e-02,  6.3163e-02,  3.6053e-02,
           -5.1841e-02,  3.4318e-01,  1.6581e-01,  2.0225e-01,  4.4640e-03,
           -8.3265e-02, -1.3794e-01,  5.6078e-02,  1.4680e-01, -6.8789e-02,
           -6.7228e-02,  6.6863e-02, -8.6546e-02,  9.2684e-03,  1.2985e-01,
            2.5971e-02,  6.3161e-03,  2.5147e-01, -9.6953e-02,  1.4555e-02,
            9.7402e-02,  7.6579e-03,  6.8055e-02,  1.1170e-01, -6.5479e-04,
            2.5478e-02,  1.0764e-01,  1.1350e-01,  1.8005e-02]],

         [[-1.2629e-01, -1.2274e-01,  3.0497e-02,  1.7078e-01, -5.2131e-02,
            8.9855e-03, -9.8054e-02,  6.3577e-02,  8.2126e-03,  3.1536e-02,
           -4.1572e-02, -9.1919e-02, -6.4122e-02, -9.8264e-02, -5.1532e-02,
           -1.6412e-01,  5.8688e-02,  1.7184e-02, -4.4022e-02,  3.7365e-01,
           -6.9990e-02, -6.1948e-02,  1.3074e-01, -1.2341e-01, -2.9806e-01,
            4.8295e-01, -1.6354e-01,  5.5501e-01, -8.0332e-02,  1.5715e-01,
            1.3784e-01,  4.6067e-02,  2.0675e-02, -1.6847e-01, -2.2787e-02,
            2.4238e-01, -2.4683e-01,  1.4019e-01, -2.7187e-01, -2.5089e-02,
            5.4782e-02,  1.3862e-01,  2.7143e-02, -1.6160e-01,  3.0098e-01,
            1.1381e-01, -7.5404e-02,  1.0135e-04, -1.2100e-01, -3.4854e-02,
           -9.5403e-02,  1.5441e-01, -4.6064e-02,  9.3889e-03,  1.9940e-02,
           -1.2487e-01, -9.6878e-02,  9.6432e-02, -8.8213e-02, -6.6104e-02,
            5.1369e-02,  6.3660e-02, -2.9971e-01, -3.3485e-02]],

         [[ 6.9914e-01,  1.6028e-02,  7.5478e-02, -1.0947e-01,  2.4731e-01,
           -5.9729e-01, -8.3814e-02, -2.1167e-02,  6.1097e-02,  7.1677e-02,